// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYF9a_WvqUwBULYc8MXos_nba-_mrW17U',
    appId: '1:230924032629:web:5b0b7e10e88959a3db763c',
    messagingSenderId: '230924032629',
    projectId: 'cityinsight-61c09',
    authDomain: 'cityinsight-61c09.firebaseapp.com',
    storageBucket: 'cityinsight-61c09.appspot.com',
    measurementId: 'G-VV7WJRCEZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuChYLRuxAIKSxM1cToaIeHXDQm0IVeiI',
    appId: '1:230924032629:android:cd3e643bfa91a00bdb763c',
    messagingSenderId: '230924032629',
    projectId: 'cityinsight-61c09',
    storageBucket: 'cityinsight-61c09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlRxCPmp4hFwWgs9MBshlQP9YtyMYgMe4',
    appId: '1:230924032629:ios:2a5132377e15cc8edb763c',
    messagingSenderId: '230924032629',
    projectId: 'cityinsight-61c09',
    storageBucket: 'cityinsight-61c09.appspot.com',
    iosBundleId: 'com.example.cityinsightMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlRxCPmp4hFwWgs9MBshlQP9YtyMYgMe4',
    appId: '1:230924032629:ios:2a5132377e15cc8edb763c',
    messagingSenderId: '230924032629',
    projectId: 'cityinsight-61c09',
    storageBucket: 'cityinsight-61c09.appspot.com',
    iosBundleId: 'com.example.cityinsightMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYF9a_WvqUwBULYc8MXos_nba-_mrW17U',
    appId: '1:230924032629:web:6b39e7c77a7b5ab7db763c',
    messagingSenderId: '230924032629',
    projectId: 'cityinsight-61c09',
    authDomain: 'cityinsight-61c09.firebaseapp.com',
    storageBucket: 'cityinsight-61c09.appspot.com',
    measurementId: 'G-1PJTWP0E9H',
  );
}
